# Generated by Django 3.0.5 on 2021-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_authtok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtok',
            name='idToken',
            field=models.CharField(max_length=2500),
        ),
    ]
