# Generated by Django 3.0.5 on 2021-02-24 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0003_auto_20210224_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='cloudToken',
            field=models.CharField(default=django.utils.timezone.now, max_length=2500),
            preserve_default=False,
        ),
    ]
