# Generated by Django 3.0.5 on 2021-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
