# Generated by Django 3.0.5 on 2021-02-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_courses_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
