# Generated by Django 3.0.5 on 2021-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
