# Generated by Django 3.0.5 on 2021-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0005_auto_20210215_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
