# Generated by Django 3.0.5 on 2021-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0006_auto_20210215_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(to='swap.courses'),
        ),
    ]
